name: Docker Image CI

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Determine branch
      id: branch
      run: echo "::set-output name=branch::${{ github.ref }}"

    - name: Set image tag suffix
      id: set_suffix
      run: |
        BRANCH=${{ steps.branch.outputs.branch }}
        if [ "$BRANCH" == "refs/heads/main" ]; then
          SUFFIX="release"
        else
          SUFFIX="dev"
        fi
        echo "::set-output name=suffix::$SUFFIX"

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE: dolphindatabase/visiona-front
      run: |
        IMAGE_TAG=latest
        SUFFIX=${{ steps.set_suffix.outputs.suffix }}
        FINAL_TAG="$IMAGE_TAG-$SUFFIX"
        docker build -t $DOCKER_IMAGE:$FINAL_TAG .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push $DOCKER_IMAGE:$FINAL_TAG
